import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './providers';
import './globals.css';
import NavLink from './components/NavLink';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Nextjs nodemailer',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={inter.className}>
				<Providers>
					<NavLink />
					{children}
				</Providers>
			</body>
		</html>
	);
}
